/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_seetaface6_model_FaceDetector */

#ifndef _Included_com_seetaface6_model_FaceDetector
#define _Included_com_seetaface6_model_FaceDetector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_seetaface6_model_FaceDetector
 * Method:    construct
 * Signature: (Lcom/seetaface6/model/SeetaModelSetting;)V
 */
JNIEXPORT void JNICALL Java_com_seetaface6_model_FaceDetector_construct
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_seetaface6_model_FaceDetector
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_seetaface6_model_FaceDetector_dispose
  (JNIEnv *, jobject);

/*
 * Class:     com_seetaface6_model_FaceDetector
 * Method:    Detect
 * Signature: (Lcom/seetaface6/model/SeetaImageData;)[Lcom/seetaface6/model/SeetaRect;
 */
JNIEXPORT jobjectArray JNICALL Java_com_seetaface6_model_FaceDetector_Detect
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_seetaface6_model_FaceDetector
 * Method:    set
 * Signature: (Lcom/seetaface6/model/FaceDetector/Property;D)V
 */
JNIEXPORT void JNICALL Java_com_seetaface6_model_FaceDetector_set
  (JNIEnv *, jobject, jobject, jdouble);

/*
 * Class:     com_seetaface6_model_FaceDetector
 * Method:    get
 * Signature: (Lcom/seetaface6/model/FaceDetector/Property;)D
 */
JNIEXPORT jdouble JNICALL Java_com_seetaface6_model_FaceDetector_get
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_seetaface6_model_FaceDetector_Property */

#ifndef _Included_com_seetaface6_model_FaceDetector_Property
#define _Included_com_seetaface6_model_FaceDetector_Property
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
