/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_seetaface6_model_FaceRecognizer */

#ifndef _Included_com_seetaface6_model_FaceRecognizer
#define _Included_com_seetaface6_model_FaceRecognizer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_seetaface6_model_FaceRecognizer
 * Method:    construct
 * Signature: (Lcom/seetaface6/model/SeetaModelSetting;)V
 */
JNIEXPORT void JNICALL Java_com_seetaface6_model_FaceRecognizer_construct
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_seetaface6_model_FaceRecognizer
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_seetaface6_model_FaceRecognizer_dispose
  (JNIEnv *, jobject);

/*
 * Class:     com_seetaface6_model_FaceRecognizer
 * Method:    GetCropFaceWidth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_seetaface6_model_FaceRecognizer_GetCropFaceWidth
  (JNIEnv *, jobject);

/*
 * Class:     com_seetaface6_model_FaceRecognizer
 * Method:    GetCropFaceHeight
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_seetaface6_model_FaceRecognizer_GetCropFaceHeight
  (JNIEnv *, jobject);

/*
 * Class:     com_seetaface6_model_FaceRecognizer
 * Method:    GetCropFaceChannels
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_seetaface6_model_FaceRecognizer_GetCropFaceChannels
  (JNIEnv *, jobject);

/*
 * Class:     com_seetaface6_model_FaceRecognizer
 * Method:    GetExtractFeatureSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_seetaface6_model_FaceRecognizer_GetExtractFeatureSize
  (JNIEnv *, jobject);

/*
 * Class:     com_seetaface6_model_FaceRecognizer
 * Method:    CropFace
 * Signature: (Lcom/seetaface6/model/SeetaImageData;[Lcom/seetaface6/model/SeetaPointF;Lcom/seetaface6/model/SeetaImageData;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_seetaface6_model_FaceRecognizer_CropFace
  (JNIEnv *, jobject, jobject, jobjectArray, jobject);

/*
 * Class:     com_seetaface6_model_FaceRecognizer
 * Method:    ExtractCroppedFace
 * Signature: (Lcom/seetaface6/model/SeetaImageData;[F)Z
 */
JNIEXPORT jboolean JNICALL Java_com_seetaface6_model_FaceRecognizer_ExtractCroppedFace
  (JNIEnv *, jobject, jobject, jfloatArray);

/*
 * Class:     com_seetaface6_model_FaceRecognizer
 * Method:    Extract
 * Signature: (Lcom/seetaface6/model/SeetaImageData;[Lcom/seetaface6/model/SeetaPointF;[F)Z
 */
JNIEXPORT jboolean JNICALL Java_com_seetaface6_model_FaceRecognizer_Extract
  (JNIEnv *, jobject, jobject, jobjectArray, jfloatArray);

/*
 * Class:     com_seetaface6_model_FaceRecognizer
 * Method:    CalculateSimilarity
 * Signature: ([F[F)F
 */
JNIEXPORT jfloat JNICALL Java_com_seetaface6_model_FaceRecognizer_CalculateSimilarity
  (JNIEnv *, jobject, jfloatArray, jfloatArray);

#ifdef __cplusplus
}
#endif
#endif
